### PR TITLE
Remove ansible_managed

### PR DESCRIPTION
**Pull request by ghost**
It's only defined when using the template module

### CODE REVIEW

**Review by SlothOfAnarchy — CHANGES_REQUESTED** [review]
But the files are still ansible-managed? Can't you access the variable another way?

**Comment by ghost** [comment]
No

**Comment by SlothOfAnarchy** [comment]
You could add a static comment "Ansible managed - do not edit" instead?

**Comment by ghost** [comment]
This is literally more annoying than the indentation of tables

**Comment by SlothOfAnarchy** [comment]
You know, if you really want a clean solution, just template it.

**Review by SlothOfAnarchy — APPROVED** [review]

**Pull request merged**
